#!/usr/bin/env python3
"""scripts/backtest_ifd.py
Simple backtest utility that reads an `internal` scored CSV (generated by
`weekly_events_update.py`) and the cached market_data.csv and computes
simple N-day returns for each trade. Outputs a CSV summary and a small
aggregated report.

Usage:
    python3 scripts/backtest_ifd.py --internal logs/events_scored_YYYYMMDD_HHMM_internal.csv
"""
import argparse
import pandas as pd
from datetime import timedelta
import os

def find_price_at_or_after(market_df, dt, symbol):
    # market_df expected to have 'date' column
    # find first market row with date >= dt
    m = market_df[market_df['date'] >= dt]
    if m.empty:
        return None
    return float(m.iloc[0].get(symbol, float('nan')))


def check_tp_sl_hit(market_df, entry_dt, symbol, entry_price, TP, SL, max_days=7):
    # Check the market series from entry_dt up to entry_dt + max_days for TP/SL hits.
    end_dt = entry_dt + pd.Timedelta(days=max_days)
    window = market_df[(market_df['date'] >= entry_dt) & (market_df['date'] <= end_dt)].copy()
    if window.empty:
        return {'hit': None, 'hit_price': None, 'hit_time': None}
    # For BUY: TP if any price >= TP, SL if any price <= SL. Determine earliest hit.
    window = window.reset_index(drop=True)
    hit_type = None
    hit_time = None
    hit_price = None
    for i, row in window.iterrows():
        price = float(row.get(symbol, float('nan')))
        if pd.isna(price):
            continue
        # check TP first for BUY
        if not pd.isna(TP) and price >= TP:
            hit_type = 'TP'
            hit_time = row['date']
            hit_price = price
            break
        if not pd.isna(SL) and price <= SL:
            hit_type = 'SL'
            hit_time = row['date']
            hit_price = price
            break
    return {'hit': hit_type, 'hit_price': hit_price, 'hit_time': hit_time}

def main(internal_csv, market_cache=None, days=[1,3,7], out_csv=None):
    internal_csv = os.path.expanduser(internal_csv)
    if not os.path.isfile(internal_csv):
        raise SystemExit(f"internal CSV not found: {internal_csv}")
    df = pd.read_csv(internal_csv)
    market_cache = market_cache or os.path.expanduser('~/Desktop/CFD3_AutoSystem/market_data.csv')
    if not os.path.isfile(market_cache):
        raise SystemExit(f"market cache not found: {market_cache}")
    market = pd.read_csv(market_cache)
    market['date'] = pd.to_datetime(market['date'])
    # normalize tz to naive for comparisons
    try:
        market['date'] = market['date'].dt.tz_convert(None)
    except Exception:
        try:
            market['date'] = market['date'].dt.tz_localize(None)
        except Exception:
            pass
    df['date'] = pd.to_datetime(df['date'])
    try:
        df['date'] = df['date'].dt.tz_convert(None)
    except Exception:
        try:
            df['date'] = df['date'].dt.tz_localize(None)
        except Exception:
            pass

    results = []
    for _, r in df.iterrows():
        entry = r.get('entry')
        src = r.get('entry_source')
        d0 = r.get('date')
        if pd.isna(entry) or pd.isna(d0) or pd.isna(src):
            continue
        d0 = pd.to_datetime(d0)
        row_res = {'text': r.get('text',''), 'entry_source': src, 'entry': entry}
        for n in days:
            future_dt = d0 + pd.Timedelta(days=n)
            price_n = find_price_at_or_after(market, future_dt, src)
            if price_n is None or pd.isna(price_n):
                row_res[f'return_{n}d'] = None
            else:
                try:
                    ret = (float(price_n) - float(entry)) / float(entry)
                    # if SELL, invert sign
                    if str(r.get('signal','')).upper() == 'SELL':
                        ret = -ret
                    row_res[f'return_{n}d'] = ret
                except Exception:
                    row_res[f'return_{n}d'] = None

        # TP/SL hit detection (within max days)
        try:
            TP = float(r.get('TP')) if not pd.isna(r.get('TP')) else None
        except Exception:
            TP = None
        try:
            SL = float(r.get('SL')) if not pd.isna(r.get('SL')) else None
        except Exception:
            SL = None
        try:
            hit = check_tp_sl_hit(market, d0, src, float(entry), TP, SL, max_days=max(days))
            row_res.update(hit)
        except Exception:
            row_res.update({'hit': None, 'hit_price': None, 'hit_time': None})
        results.append(row_res)

    out = pd.DataFrame(results)
    if out_csv:
        out.to_csv(out_csv, index=False, encoding='utf-8-sig')
        print('Saved backtest summary to', out_csv)
    # print aggregated stats
    print('\nBacktest summary:')
    for n in days:
        col = f'return_{n}d'
        if col in out.columns:
            vals = out[col].dropna()
            if len(vals):
                print(f' {n}d: count={len(vals)} mean={vals.mean():.4f} win_rate={(vals>0).mean():.2%}')
            else:
                print(f' {n}d: no data')

    # Save a simple plot (boxplot of available returns) if matplotlib available
    try:
        import matplotlib.pyplot as plt
        plot_cols = [f'return_{n}d' for n in days if f'return_{n}d' in out.columns]
        if plot_cols:
            fig, ax = plt.subplots()
            data = [out[c].dropna() for c in plot_cols]
            ax.boxplot(data, labels=[c.replace('return_','') for c in plot_cols])
            ax.set_title('IFD Backtest Returns')
            out_plot = out_csv.replace('.csv','_plot.png') if out_csv else 'backtest_plot.png'
            fig.savefig(out_plot)
            print('Saved backtest plot to', out_plot)
    except Exception:
        pass

if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--internal', required=True, help='path to internal scored csv')
    p.add_argument('--market', help='path to market_data.csv (optional)')
    p.add_argument('--out', help='output csv path for per-trade returns')
    p.add_argument('--days', nargs='+', type=int, default=[1,3,7])
    args = p.parse_args()
    main(args.internal, market_cache=args.market, days=args.days, out_csv=args.out)
